### ISSUE TITLE
Can't be activated

### ISSUE THREAD

**Issue by GhostwheelX** [zarmstrong/fvtt-hide-buttons#1]
This module does not appear in the list of modules that you can activate in the "Manage Modules" page.

**Comment by zarmstrong** [comment]
Need more info. What version of Foundry? What game system? What version of the module?

**Comment by GhostwheelX** [comment]
Foundry Version: 0.8.8
System: DnD5e - Fifth Edition System 1.3.6
Module version: 1.0.2

**Comment by zarmstrong** [comment]
This was due to the module being limited to pf2e system. I don't know why I did that, but the latest release, 1.0.3, fixes this!
